### ISSUE TITLE
Contact Layout Editor 2.0.2 displays the Key Relationships block twice on Contacts

### ISSUE THREAD

**Issue by agileware-justin** [civicrm/org.civicrm.contactlayout#102]
Contact Layout Editor 2.0.2 displays the Key Relationships block twice on Contacts. Using CiviCRM 5.38.0.

### Example contact display with Contact Layout Editor 1.9.0 installed

Single "Employer of" relationship block is shown.

![Screenshot_20210618_CEL_v1-9-0](https://user-images.githubusercontent.com/58866555/122508858-04197f00-d046-11eb-821b-24416f649692.png)

### Example contact display with Contact Layout Editor 2.0.2 installed

Two "Employer of" relationship blocks are shown.

![Screenshot_20210618_CEL_v2-0-2](https://user-images.githubusercontent.com/58866555/122508854-02e85200-d046-11eb-8329-5401b9f97a3e.png)

### Contact Layout Editor Configuration

The same / unchanged Contact Layout Editor Configuration is used for both 1.9.0 and 2.0.2.

![Screenshot_20210618_145702](https://user-images.githubusercontent.com/58866555/122508960-3d51ef00-d046-11eb-8cfb-008c3925948c.png)

![Screenshot_20210618_145651](https://user-images.githubusercontent.com/58866555/122508968-3e831c00-d046-11eb-86df-afa39fa4e7f9.png)

Agileware Ref: CIVICRM-1783

**Comment by colemanw** [comment]
Looks like this was caused by fixing #96.
I've reverted commit 50ce952 and published v2.0.3.

**Comment by agileware-justin** [comment]
Thanks very much @colemanw for fixing this problem so quickly, much appreciated. Have a good one! :)
