### ISSUE TITLE
"You have requested a non-existent service "angularjs.loader"

### ISSUE THREAD

**Issue by circleinteractive** [civicrm/org.civicrm.contactlayout#104]
Hi

I get this when enabling the extension and then visiting /civicrm/admin/contactlayout (civicrm 5.35.2)

$Fatal Error Details = array:3 [
  "message" => "You have requested a non-existent service "angularjs.loader"."
  "code" => null
  "exception" => Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException {#1213
    -id: "angularjs.loader"
    -sourceId: null
    -alternatives: []
    #message: "You have requested a non-existent service "angularjs.loader"."
    #code: 0
    #file: "/var/www/drupal758civi5352/sites/all/modules/civicrm/vendor/symfony/dependency-injection/Container.php"
    #line: 348
    trace: {
      /var/www/drupal758civi5352/sites/all/modules/civicrm/vendor/symfony/dependency-injection/Container.php:348 { …}
      /var/www/drupal758civi5352/sites/all/modules/civicrm/Civi.php:108 {
        › public static function service($id) {
        ›   return \Civi\Core\Container::singleton()->get($id);
        › }
        arguments: {
          $id: "angularjs.loader"
        }
      }
      /var/sites/foo.org/civicrm_extensions/org.civicrm.contactlayout-2.0.3/CRM/Contactlayout/Page/Base.php:35 { …}
      /var/www/drupal758civi5352/sites/all/modules/civicrm/CRM/Core/Invoke.php:312 { …}
      /var/www/drupal758civi5352/sites/all/modules/civicrm/CRM/Core/Invoke.php:68 { …}
      /var/www/drupal758civi5352/sites/all/modules/civicrm/CRM/Core/Invoke.php:36 { …}
      /var/www/drupal758civi5352/sites/all/modules/civicrm/drupal/civicrm.module:458 { …}
      /var/www/drupal758civi5352/includes/menu.inc:527 { …}
      /var/www/drupal758civi5352/index.php:21 { …}
    }
  }
]

Thanks

Bails

**Comment by colemanw** [comment]
You are using a version of this extension which is too new for your version of CiviCRM.

Civi isn't supposed to let you download extensions that aren't compatible with your version of CiviCRM so perhaps you did so manually?

**Comment by matt-circle** [comment]
Hi Coleman,

Thanks for this. I've checked out a version (v1.9.0) compatible with the Civi version we're using which has installed all okay.
I think this is safe to close.

Thanks,
Matt
