### ISSUE TITLE
Invalid field 'uf_group_id.is_active'

### ISSUE THREAD

**Issue by wintermoor** [civicrm/org.civicrm.contactlayout#106]
CiviCRM 5.36, Drupal 7, PHP 7.4.3
contactlayout v2.0.3

Admin can't access "Customize Data and Screen -> Contact Summary Layouts". 
Non-admin users can't access any contacts. 

Error message: 
Invalid field 'uf_group_id.is_active'

I tried contactlayout v2.0.3 because I had the same error like in https://github.com/civicrm/org.civicrm.contactlayout/issues/98 with contactlayout v1.9. Too new release , I know. But maybe you'll find the error message helpfull?

(Fixed my issue installing contactlayout v1.8.2. and no update to v1.9 like system status recommends.)

**Comment by wintermoor** [comment]
Aug 10 13:51:27  [error] 
$Fatal Error Details = array:3 [
  "message" => "Invalid field 'uf_group_id.is_active'"
  "code" => null
  "exception" => API_Exception {#2307
    -extraParams: array:1 [
      "error_code" => 0
    ]
    #message: "Invalid field 'uf_group_id.is_active'"
    #code: 0
    #file: "/var/www/html/sites/all/modules/civicrm/Civi/Api4/Query/Api4SelectQuery.php"
    #line: 568
    trace: {
      /var/www/html/sites/all/modules/civicrm/Civi/Api4/Query/Api4SelectQuery.php:568 {
        › if ($strict && !$field) {
        ›   throw new \API_Exception("Invalid field '$fieldName'");
        › }
      }

**Comment by colemanw** [comment]
I recommend upgrading CiviCRM and this extension to the latest versions.
