### ISSUE TITLE
Uncaught ReferenceError: label is not defined on multilingual environment

### ISSUE THREAD

**Issue by shaneonabike** [civicrm/org.civicrm.contactlayout#115]
I seem to have come across a strange issue when creating new blocks.

**Reproduce:**

1. Setup a multilingual environment
2. Create a new Layout
2. Create a new block
3. Change the title to something help, for example ```Contact Details```
4. Add one custom field, demographics fields (i.e. Gender and Date of Birth)
5. Save
6. Drag and drop it into your blocks setting and expand or Edit the block

**What happens:**

You can no longer edit the new block and/.or add fields into the newly created block. The error I get in my browser console is 

```
Uncaught ReferenceError: label is not defined
    at eval (eval at <anonymous> (lodash.min.js:75:591), <anonymous>:3:477)
    at Object.render (backbone.marionette.js?r=HV6uc:1231:12)
    at child.render (backbone.marionette.js?r=HV6uc:1457:36)
    at child.r [as render] (lodash.min.js:25:62)
    at Marionette.Region.show (backbone.marionette.js?r=HV6uc:910:10)
    at child.onRender (crm.designer.js?r=HV6uc:618:20)
    at child.triggerMethod (backbone.marionette.js?r=HV6uc:565:21)
    at child.render (backbone.marionette.js?r=HV6uc:1462:10)
    at child.render (backbone.marionette.js?r=HV6uc:1920:55)
    at child.r [as render] (lodash.min.js:25:62)
```

No message appears in the log files.
![Selection_007](https://user-images.githubusercontent.com/1126026/155150944-532e323a-a20c-4b2c-ae0a-02297d897531.png)

**What you expect:**

To be able to edit the fields and all the fields are stored properly.

**Comment by shaneonabike** [comment]
![Peek 2022-02-22 10-37](https://user-images.githubusercontent.com/1126026/155154374-ee0d5cb5-f7b8-4b85-bb4a-56eccb32bac9.gif)

**Comment by colemanw** [comment]
@shaneonabike I appreciate the detailed bug report. Unfortunately it's a bit obscure, and the issue is with some older technology (the old profile-builder popup). I'm not sure when/if this will get prioritized, but there is a workaround: instead of relying on the profile-builder popup, you can edit the profile the old way, by going to **Administer -> Customize Data & Screens -> Profiles**.

**Comment by shaneonabike** [comment]
Hi @colemanw yes that's what I ultimately did in order to make it work. I'm not sure it's that obscure but is there a way to just disable this feature maybe? Then it would force folks to use the actual Profile as you suggest to add it?
