### ISSUE TITLE
Does not work anymore after CiviCRM Update for contacts with limited access

### ISSUE THREAD

**Issue by mariav0** [civicrm/org.civicrm.contactlayout#125]
Yesterday I've updated CiviCRM on Version 5.56.2 and since then the CLM does not work for specific roles (with limited access) anymore.
It still works for any other role in CiviCRM.

Permissions given on this role:
- add contacts
- view my contact details
- edit my contact details
- View / download files including images and photos
- view profiles
- View all custom fields regardless of ACL rules
- access CiviCRM Backend und API 
- view contact summary

The contacts that these users see are controlled by the Group Admin extension.

CLM version: 2.1.3

**Comment by colemanw** [comment]
@mariav0 do you get any error message?

**Comment by mariav0** [comment]
Hi @colemanw, yes.
Log viewer shows:
 [warning] ContactLayout "Ansicht für BV
" cannot filter on nonexistent group "Ansicht_BV_169".

**Comment by lbl-knts** [comment]
Same here, but with a slightly different setting. the top layout is for a group where people are allowed to see everything (admins). The second layout below is for a group of users who are highly regulated. As a result, everyone sees the admin layout.

**Comment by colemanw** [comment]
@mariav0 @lbl-knts can you please check to see if this patch fixes the bug for you? If so please leave a comment on that PR so we can get it merged and released :)

**Comment by mariav0** [comment]
@colemanw Sorry for my late response. Since you have already merged and released it, I only want to say thank you very much :)

**Comment by colemanw** [comment]
You're welcome @mariav0 :)

**Comment by lbl-knts** [comment]
I have tested it now as well. Works perfectly!
