### ISSUE TITLE
Custom fields with radio buttons and many choices exceed page width

### ISSUE THREAD

**Issue by github-wcha** [civicrm/org.civicrm.contactlayout#132]
When adding custom fields to a contact layout, custom fields that have a lot of choices as radio buttons expand the field horizontally, sometimes beyond the width of the page.

![image](https://github.com/civicrm/org.civicrm.contactlayout/assets/77943875/7c462667-b50b-4409-9348-a06765c06b0f)

I initially thought this might be Shoreditch related, but I've also observed it now on a clean install of CiviCRM without Shoreditch enabled.

**Comment by colemanw** [comment]
@github-wcha did you try setting the "Options Per Line" setting for your field?
![image](https://github.com/civicrm/org.civicrm.contactlayout/assets/2874912/24a5eb16-eeff-4826-83b5-bd6e5fe7b362)

**Comment by github-wcha** [comment]
Thanks @colemanw! That did it. Somehow in all my years of using CiviCRM I'd managed to totally ignore the existence of that option...
