### ISSUE TITLE
Contact subtype to apply a layout is not retained after saving changes

### ISSUE THREAD

**Issue by quimgil** [civicrm/org.civicrm.contactlayout#135]
We are setting up fresh installation and we are finding a very basic problem: we define a contact subtype to show the layout, but this information is lost after clicking Save All. The type remains.

There seems to be a problem caused by the interaction of various layouts pointing to different subtypes. We have, inthis order:

1. a layout for Projects > Wiki Projects
2. A layout for Organizations > Committees
3. A layout for Organizations > Affiliates
4. A layout for all Individuals

If we save Wiki Projects as a subtype and then go to the other layout and save Committees as subtypes, when we go back to the Wiki Projects layout.... the Subtype fiels is empty again. If we save "Wiki Projects" and we go back to "Committees"... then the Committees layout has the subtype empty. Very annoying.  :) 

I have tried to save once and then come back later after a reboot just in case there was some nasty browser cache or something (unlikely that this is the problem, but I didn't know what else to try). This didn't make any difference.

**Comment by quimgil** [comment]
I found a (very logical) way to bypass this bug. Yay for sleeping!  🙂 

I had created layouts for subtypes but not for the corresponding types (i.e. a layout for Affiliates subtype without having a layout for the Organizations type). Now I have created layouts for the three types of contacts, and the problem has gone away. The subtype layouts stay after having been saved, and I can move onto other things.

The bug is still there, but won't hit it again in our instance. I suppose the extension is not intended to provide layouts for subtypes before having layouts for their types. In that case, there should be an error message instead of silently not saving / removing subtypes defined.

**Comment by colemanw** [comment]
Thanks for reporting @quimgil 
I've tried and failed to reproduce this bug. On a stock Civi instance I
1. Created a layout for Organization: Team
2. Created a layout for Organization: Sponsor
3. Saved, left the screen, came back, everything was fine.
4. Created a layout for Individual
5. Saved, left the screen, came back, everything was fine.

Not sure what else to try.

**Comment by quimgil** [comment]
Thank you, @colemanw. Well, maybe it was a glitch, maybe it is something fixed in the latest versions. I found this problem in a new instance with a first cohort of users joining and my priority was to avoid the problem rather than diagnose. It is working now, and I don't want to undo the layouts for the primary types to avoid disruption in the CRM.

**Comment by colemanw** [comment]
Ok I'll go ahead and close until/unless we get a reproducible bug.
