### ISSUE TITLE
Database table should be InnoDB

### ISSUE THREAD

**Issue by mattwire** [civicrm/org.civicrm.contactlayout#14]
No defaults are specified in auto_install.sql so at least on my system the table gets created as MyISAM with latin_swedish_ci character set!

Need to include:
` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;`

at the end of the table definition.

**Comment by colemanw** [comment]
Hmm, the tables were created automatically with `civix`. @totten is this a known issue with the civix autoinstaller?

**Comment by philmb** [comment]
I confirm that my table was also created as MyISAM, but with utf8_general_ci

**Comment by mattwire** [comment]
So the sql files shipped with CiviCRM core include these defaults for each table:
`)  ENGINE=InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci  ;`

I guess this should be fixed with civix as well, maybe something I'll get chance to look at during the sprint.  But for now could it be added to the auto_install for this extension?
