### ISSUE TITLE
Fatal error: Type of SmartyCompilerException::$line must be int (as in class Exception) vendor/civicrm/civicrm-packages/smarty3/vendor/smarty/smarty/libs/sysplugins/smartycompilerexception.php on line 8

### ISSUE THREAD

**Issue by allantinashemuzeya** [civicrm/org.civicrm.contactlayout#146]
Upgraded from 5.44 to 5.69 and the moment its using smarty3 the extension breaks, I'm not sure if this is already fixed but I'm on the latest version 2.3.1

<img width="744" alt="Screenshot 2024-06-14 at 17 43 05" src="https://github.com/civicrm/org.civicrm.contactlayout/assets/68616320/de5217bf-c2d5-494f-9313-9ea818ab167c">

**Comment by colemanw** [comment]
Try upgrading to Smarty4, it has better compatibility with PHP 8.

**Comment by allantinashemuzeya** [comment]
Thank you I will try this

**Comment by allantinashemuzeya** [comment]
Thank you so much @colemanw the issue is not in smarty4. 

Thank you so much for your prompt response. ❤️

**Comment by colemanw** [comment]
You're welcome @allantinashemuzeya !
