### ISSUE TITLE
Don't show custom data for different contact type

### ISSUE THREAD

**Issue by mattwire** [civicrm/org.civicrm.contactlayout#15]
If you add a layout with custom data for two different contact types (eg. an individual and an organisation) the headers for both blocks are always visible but the fields are correctly shown only if the custom data type matches the contact type.
The whole block should probably not be visible in this situation.

**Comment by colemanw** [comment]
@mattwire what about creating different layouts for your different contact types?

**Comment by mattwire** [comment]
@colemanw Yes that works :-) Just thought it might be nice if the blocks did not show up if they were not meant for that contact type, but don't know how easy it is to actually do that.

**Comment by colemanw** [comment]
@mattwire care to try #34
