### ISSUE TITLE
profiles don't save with contact id in them

### ISSUE THREAD

**Issue by eileenmcnaughton** [civicrm/org.civicrm.contactlayout#16]
Our admins created a 'quick info' profile for pride of place but they included 'contact id' which makes sense for 'view mode' - unfortunately it stopped edit mode from saving on that profile. I thought changing it to 'view only' should have been enough to make it work but we had to remove it again (which we have done)

**Comment by colemanw** [comment]
Try this: https://github.com/civicrm/org.civicrm.contactlayout/pull/20
