### ISSUE TITLE
tag profile doesn't work

### ISSUE THREAD

**Issue by eileenmcnaughton** [civicrm/org.civicrm.contactlayout#17]
Our users created a profile with tags as the field & it won't save on edit - at least when removing the last row

**Comment by colemanw** [comment]
@eileenmcnaughton I've investigated this and found that there is some inconsistency with the incoming data from a quickform profile vs what the api3 profile:submit is expecting.
Trying to think of the least hackish way to fix this.

**Comment by eileenmcnaughton** [comment]
So there are 2 issues - 1 is validation (accepting '1,2,3') 2 is doing deletes as well as creates - this latter has to go into the Profile.submit api itself

**Comment by eileenmcnaughton** [comment]
What about in _civicrm_api3_api_match_pseudoconstant_value testing unpacking any commas to see if all parts validate if the whole doesn't?

**Comment by colemanw** [comment]
@eileenmcnaughton please check that this is fixed by https://github.com/civicrm/civicrm-core/pull/12825
