### ISSUE TITLE
Default ID, Type, Tags is empty

### ISSUE THREAD

**Issue by samuelsov** [civicrm/org.civicrm.contactlayout#18]
With or without tags defined on the contact, the predefined block "ID, Type, Tags" seems to be always empty.

**Comment by colemanw** [comment]
@samuelsov that block requires CiviCRM version 5.5.

**Comment by eileenmcnaughton** [comment]
in general the extension has 5.5 as a minimum doesn't it?

**Comment by colemanw** [comment]
Yes.

**Comment by colemanw** [comment]
@samuelsov I'm going to close this. Please upgrade to CiviCRM 5.5 and try again. If the issue persists feel free to reopen.
