### ISSUE TITLE
Employer field in profiles is not equivalent to the one in the built in blocks

### ISSUE THREAD

**Issue by eileenmcnaughton** [civicrm/org.civicrm.contactlayout#22]
The employer field doesn't offer an autoselect & when saved it creates a new relationship - but does not end the prior one

**Comment by nganivet** [comment]
Don't know if it would be scope creep, but a number of my customer complained about this field being restricted to just one employer. Nowadays a lot of people have multiple employers (and a different job title with each of these). As we refactor the contact screen we might want to take this into account.

**Comment by eileenmcnaughton** [comment]
hmm - the complaint that triggered this is that the field is not just doing one employer like the core behaviour. I think the relationship block might make multiple optional though - I think that was a patch @colemanw did

 Note the contact screen isn't being refactored - this is a leap by extension - no change to core on this

**Comment by nganivet** [comment]
Sorry about the confusion, I meant that we might allow for displaying (and potentially editing) multiple employers in this extension. So the employers section would look similar to the phone / address sections.

**Comment by eileenmcnaughton** [comment]
@nganivet the way the extension works is very pluggable - so you can declare extra blocks to be available - check the relationship block extension - which allows multiple relationships - it probably does what you want

**Comment by eileenmcnaughton** [comment]
@nganivet I *think* it can do  that - although I haven't tested that exact scenario.

**Comment by eileenmcnaughton** [comment]
@nganivet but that doesn't resolve my original issue - in that there is the hope of embedding the employer field (behaving as per the built in one) on a profile block on the contact summary.

**Comment by eileenmcnaughton** [comment]
(it may be that the solution is to change Relationship Block to permit multiple blocks on one page - but I'm hoping to be able to integrate existing core behaviour into a profile block as first preference)

**Comment by nganivet** [comment]
Would it not resolve your issue if the 'Employer' block was substituted with a 'Relationships' block restricte to employer/employee relationships? If there is just one employer relationship for that contact I imagine it would display very similarly to the current Employer block (at least the Phone and Email blocks do).

**Comment by eileenmcnaughton** [comment]
@nganivet right - but 2 things
1) they already have a relationship block on their summary (with 4 relationship types in it). The relationship block extension doesn't currently support multiple blocks on a page
2) since we have switched to shoreditch the difference between it being part of the same block & it's own block is very evident - with a lot of space around it etc. We can live with that if we have to - but my first choice would be to make the current employer field 'work properly' in profiles

**Comment by colemanw** [comment]
I think we can have the best of both here. This extension can fix the employer field to act like it does in the relationship block extension - handling one or more employer using an autocomplete to select them.

**Comment by nganivet** [comment]
@eileenmcnaughton it was not an issue, I was just trying to propose another approach, @colemanw thanks for clarifying, that is exactly what I meant. Just to be clear, it is not one field with multiple employers, but one block that shows multiple lines, one for each employer (same UI/behavior as phone/email blocks). Each line has at minimum an Employer and Job Title fields.

**Comment by eileenmcnaughton** [comment]
@nganivet I think we are talking about one field with multiple employers. Removing them ends the relationship. Adding creates - as @colemanw says - per the relationship block extension. I think it would be good to expose a block like you propose in another extension - which could then be included in the layout by this extension.

**Comment by eileenmcnaughton** [comment]
@colemanw thanks - that fix is perfect
