### ISSUE TITLE
Extension key conflicts with an existing extension

### ISSUE THREAD

**Issue by davialexandre** [civicrm/org.civicrm.contactlayout#3]
Hi,

In CiviHR, we already have an extension with the `org.civicrm.contactssummary` key: https://github.com/compucorp/civihr/blob/staging/contactsummary/info.xml#L2. I wonder what would happen if someone tried to install both on the same site.

**Comment by colemanw** [comment]
Yikes!

@davialexandre and @jamienovick would it be possible to rename your extension to `org.civicrm.hrsummary`? I think that would be a better name for it to avoid confusion?

**Comment by colemanw** [comment]
I've gone ahead and updated the name of this extension, which is a pain, but easier to do now while it's pre-release. Although I still think renaming the HR extension would be advisable if practical to do so.

Anyone currently using this extension will need to completely uninstall it, delete it, download or clone the latest version, and reinstall. Your layouts will be erased, but any profile-based blocks or custom fields you've made will still be there. 

FYI @eileenmcnaughton @lcdservices @privaterra @mecachisenros

**Comment by privaterra** [comment]
@colemanw thanks for the head's up. I'll follow the steps you mention to use the renamed version

**Comment by eileenmcnaughton** [comment]
ouch. But agree - extension is still wip - I'm demo-ing to WMF next week now

**Comment by eileenmcnaughton** [comment]
@colemanw you could join the call if you would like? Might be interesting

**Comment by davialexandre** [comment]
Thanks @colemanw! We have dozens of sites with this extension and it would have been difficult to update all of them. 

I agree that the extension name is not good and we don't use that name format anymore, but unfortunately, we have some quite old extensions, like this one, that still need to be updated.
