### ISSUE TITLE
A bit too quiet about misconfig

### ISSUE THREAD

**Issue by eileenmcnaughton** [civicrm/org.civicrm.contactlayout#30]
In testing the current employer fix  I seem to have wound up looking at the employer rather than the employee & lo & behold everything stopped working. I was loading up an empty profile with just the buttons. As I was busy trying various patches it took a few rabbit holes to discover the reason was the profile block would not work for an Organization.  

It seems the message that would have saved head pain is in fact assigned to the tpl - but not rendered

```
          $return = TRUE;
          if (!$statusMessage) {
            $statusMessage = ts("This profile is configured for contact type '%1'. It cannot be used to edit contacts of other types.",
                array(1 => $profileSubType ? $profileSubType : $profileType));
          }
        }
      }

      if (
      in_array(
        $profileType,
        array("Membership", "Participant", "Contribution")
      )
      ) {
        $return = TRUE;
        if (!$statusMessage) {
          $statusMessage = ts('Profile is not configured for the selected action.');
        }
      }
    }

    //lets have single status message,
    $this->assign('statusMessage', $statusMessage);
```

**Comment by colemanw** [comment]
@eileenmcnaughton try #34
