### ISSUE TITLE
Display only Summary without tabs or Action/Edit buttons

### ISSUE THREAD

**Issue by danaskallman** [civicrm/org.civicrm.contactlayout#36]
Is there a way to have only the summary display, without the extra tabs and Action buttons. So basically just name and the summary details tab. The screenshot has the most minimal permissions available to a role and there are still the:

* Activities, 
* Relationships
* Groups
* Notes (no permissions applied for notes for this user role)
* Tags
* Changelog
* Code Redeemed is CiviDiscount, but does get added

![csle-only-summary-no-tabs-or-action-edit-buttons](https://user-images.githubusercontent.com/1139085/46486884-b5abef80-c7cc-11e8-869e-aa839317aa15.png)

What would be a recommended way for us to provide a summary only screen and control what tabs or menu's get displayed?

Relates to #35 in what a role or group can then do on the summary page itself.

**Comment by colemanw** [comment]
When you say Menus are you also requesting control over the Actions menu?

**Comment by danaskallman** [comment]
I guess yeah, we don't want that displayed for all who can view a group of contacts. Meaning we essentially just want to be able to provide a group of volunteers with the summary tab and whatever blocks are there and nothing else. Is that what you meant?

**Comment by danaskallman** [comment]
Of course, the contact name too!

**Comment by danaskallman** [comment]
We can definitely chat funding, I'll ping you. 

Re: permissions, I'll test in more detail and update.

**Comment by colemanw** [comment]
The tab feature was implemented so let's close this and open another issue if there's more work to do.
