### ISSUE TITLE
Contact Image Block

### ISSUE THREAD

**Issue by danaskallman** [civicrm/org.civicrm.contactlayout#37]
Is there a way to display the contact image? I don't see a block, but maybe there's another way I missed?

**Comment by colemanw** [comment]
Try adding Image URL to a custom block.

**Comment by danaskallman** [comment]
Works, thanks!

**Comment by colemanw** [comment]
I updated my master checkout but still get the error.

**Comment by colemanw** [comment]
This was fixed with 5ea9d03cf48fc9abbbbfe73a51fad3581f304549
