### ISSUE TITLE
Group data lost when editing tags

### ISSUE THREAD

**Issue by eileenmcnaughton** [civicrm/org.civicrm.contactlayout#40]
@colemanw this is a bit critical.....

If you have a tag field on your block and NOT a group field then when you edit the tag all group memberships are lost!

The patch below works I think- still testing

BUT the trickiness is that there is a little nest of compatibility going on - we are on 5.6 & I  tried upgrading both layouteditor and apiv4 locally & TBH my local is not pretty broken so I'm backing out & patching what we have for now.

HOWEVER, you have incremented the minimum version so if you put out a new release now it won't be what 5.6 people get - at the very least you should probably delete the 5.6 compatible release. Not sure what else

FYI @ejegg

```diff
index e138b72987..4fc0d57cfc 100644
--- a/sites/default/civicrm/extensions/org.civicrm.contactlayout/CRM/Contactlayout/Form/Inline/ProfileBlock.php
+++ b/sites/default/civicrm/extensions/org.civicrm.contactlayout/CRM/Contactlayout/Form/Inline/ProfileBlock.php
@@ -107,7 +107,9 @@ class CRM_Contactlayout_Form_Inline_ProfileBlock extends CRM_Profile_Form_Edit {
     $this->_action = CRM_Core_Action::UPDATE;
 
     $this->processEmployer($values);
-    $this->processGroups($values);
+    if (isset($values['group'])) {
+      $this->processGroups($values);
+    }
     civicrm_api3('Profile', 'submit', $values);
 
     // Save tagsets (not handled by profile api)
```

**Comment by colemanw** [comment]
I've fixed this and published 5.6 and 5.7 compatible releases.
