### ISSUE TITLE
Contact Summary won't save

### ISSUE THREAD

**Issue by clarkac1** [civicrm/org.civicrm.contactlayout#45]
Clicking 'Save All' after making changes does nothing - it just sits there.   In the attached screenshot I added the block 'Tenancy' but trying to save it does nothing. This is with 5.7.3 of Civi and 1.2.2 of the extension.  There was nothing in the ConfigAndLog folder.

![screenshot_20190121_112134](https://user-images.githubusercontent.com/5676413/51471528-de9dc380-1d6e-11e9-8923-e7feabf8c4f7.png)

**Comment by clarkac1** [comment]
Disabling & re-enabling the extension didn't fix the problem, but uninstalling & reinstalling has (so far) fixed it.

**Comment by colemanw** [comment]
Very odd.
Without more info I don't think we can do anything about that, but I'm glad you got it working.
Let's close this for now and reopen if the issue reappears.

**Comment by clarkac1** [comment]
No worries, this is a new installation which was moved from elsewhere so perhaps that was the cause?
