### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by eileenmcnaughton** [civicrm/org.civicrm.contactlayout#46]
We have a block with ONLY tags in in configured. 

We  get a performance issue due to the profile rule trying to find a contact match rather than just accepting the id - I'm digging into this & think it relates to $form->_mode but I'm not sure how the enotice fits in or what to make of it

**Comment by eileenmcnaughton** [comment]
So I see 2 ways to fix this - I was hoping for a non-core fix in order to be able to not make people wait for a core fix but the non-core is a bit ugly

Core fix 
https://gerrit.wikimedia.org/r/#/c/wikimedia/fundraising/crm/civicrm/+/490507/1/CRM/Profile/Form.php - basically don't generate matches if you are going to ignore them

Extension fix
- I think adding a hidden field _qf_Edit_upload_duplicate would do it....

**Comment by colemanw** [comment]
@eileenmcnaughton can you please do a PR for the core fix?

**Comment by eileenmcnaughton** [comment]
@colemanw I've added a preliminary extraction PR https://github.com/civicrm/org.civicrm.contactlayout/issues/46#issuecomment-463690886

**Comment by eileenmcnaughton** [comment]
nope not that- this https://github.com/civicrm/civicrm-core/pull/13600

**Comment by eileenmcnaughton** [comment]
I've added the core fix here https://github.com/civicrm/civicrm-core/pull/13606 - I think the enotices are unrelated

**Comment by eileenmcnaughton** [comment]
Closing this as core patch is merged & port is working for us. Have put enotices in separate issue
