### ISSUE TITLE
Compatibility with Displays relationships extension

### ISSUE THREAD

**Issue by privaterra** [civicrm/org.civicrm.contactlayout#5]
I've been able to install and create a generate template which does created a customized version of the contact information.

However, the summary of relationships that the - [relationship2summary](https://github.com/CiviCooP/org.civicoop.relationship2summary) - extension normally generates is no longer present.

Can this extension incorporate and/or support the [relationship2summary's](https://github.com/CiviCooP/org.civicoop.relationship2summary) functionality? For instance, could custom relationship types that might be created be added to the list of fields that can be selected and added to a template?

**Comment by colemanw** [comment]
Hey @privaterra - from what I can tell the `relationship2summary` extension was written as a developer howto, e.g. it does something very simple just for the purposes of showing developers how to write an extension. To that end, the git repo for that extension has a number of different branches, each of which uses a different coding technique to accomplish the same output on the screen. Why don't you try flipping through the branches (super easy to do if you checkout the extension with `git clone`) to see if one of them does work with this extension. If so, you could post some feedback to the extension author suggesting that branch be used to tag releases for use by the public.

**Comment by colemanw** [comment]
My mistake, I was thinking of a different extension.
`relationship2summary` looks a bit obsolete. Can you try using https://github.com/eileenmcnaughton/org.wikimedia.relationshipblock instead? That one does integrate with this extension.
