### ISSUE TITLE
Breaks on APIv4 4.3.0

### ISSUE THREAD

**Issue by clement888** [civicrm/org.civicrm.contactlayout#51]
Hello there,

    I have just upgraded APIv4 extension on my CIVICRM (5.10.4, Wordpress) to 4.3.0 and apparantly this broke Contact Layout Editor (no editor shown).  Reverting to 4.1.0 made everything back to normal.  You might want to take a note.

Clement

**Comment by colemanw** [comment]
@clement888 please upgrade to the latest version of both ContactLayout **and** Api4. As you noted, upgrading one but not the other will cause a break.

**Comment by clement888** [comment]
I see, i now see there is a 1.4.1 for ContactLayout which wasn't prompted by CIVICRM extension page.  I was using 1.3.1.  Thanks.
