### ISSUE TITLE
Conflict with Content Security Policy Header

### ISSUE THREAD

**Issue by clement888** [civicrm/org.civicrm.contactlayout#56]
Hello all, i had a problem running contact layout when i include a Content Security Policy header but later was able to get to it by relaxing the policy.  i thought i put the header configuration here:

Header set Content-Security-Policy "script-src 'self' 'unsafe-inline' 'unsafe-eval';"

Apparently, this affects the quick edit function on the contact summary as well. 

would there be a tighter CSP that could be used ?  Thanks.

CIVICRM 5.10.4 WP 5.0 Apache2

**Comment by colemanw** [comment]
CiviCRM api code uses `eval()` but in a safe way. Potentially we could fix this but for now try just removing that part of your CSP to see if that fixes the error.
