### ISSUE TITLE
Field value of communication style is not shown

### ISSUE THREAD

**Issue by thomas-SGB** [civicrm/org.civicrm.contactlayout#59]
Unfortunately in self designed boxes the value of communication style is not shown. With other radio fields, i.e. gender, there is no problem. 
When editing this field everything works fine. (see screenshots)

![Screenshot_2019-09-03](https://user-images.githubusercontent.com/54853415/64184435-bc733480-ce6b-11e9-9823-aa2866558760.png)
![Screenshot_2019-09-03(1)](https://user-images.githubusercontent.com/54853415/64184550-e62c5b80-ce6b-11e9-8f3e-79eb9ff59e22.png)

**Comment by colemanw** [comment]
This should fix it: https://github.com/civicrm/civicrm-core/pull/15205 - please test out and comment on that PR.

**Comment by thomas-SGB** [comment]
Thank you very much. We're happily waiting for 5.3.18 ;-)
