### ISSUE TITLE
Missing dependency org.civicrm.angularprofiles

### ISSUE THREAD

**Issue by sluc23** [civicrm/org.civicrm.contactlayout#6]
When installing I get fatal: `Unknown extension: org.civicrm.angularprofiles`

That extension is a dependency for *contactlayout* but It's not listed in the **[Requirements](https://github.com/civicrm/org.civicrm.contactlayout#requirements)** section

**Comment by colemanw** [comment]
Ok, I've added that dependency to the readme.
Note: Be sure to use the latest release of that extension, which is currently v4.7.31-1.1.2.
