### ISSUE TITLE
enotice & warning

### ISSUE THREAD

**Issue by magnolia61** [civicrm/org.civicrm.contactlayout#60]
I found two more enotices that come up lots of times
1. Notice
`Notice: Undefined index: icon in contactlayout_civicrm_pageRun() (line 155 of /var/www/vhosts/xyz/webroot/sites/all/modules/civicrm_extensions/org.civicrm.contactlayout/contactlayout.php).
`
2. Warning
`Warning: Invalid argument supplied for foreach() in CRM_Contactlayout_BAO_ContactLayout::getBlock() (line 114 of /var/www/vhosts/xyz/webroot/sites/all/modules/civicrm_extensions/org.civicrm.contactlayout/CRM/Contactlayout/BAO/ContactLayout.php).`

I have no idea what causes this but I thought you might want to know.
Regards,
RIchard

**Comment by colemanw** [comment]
1. This was addressed by #53 and should be included in the latest version 1.4.2.
2. I've just pushed up a9ba417 to fix this.
