### ISSUE TITLE
Block open in edit mode on summary page load

### ISSUE THREAD

**Issue by christianwach** [civicrm/org.civicrm.contactlayout#61]
@colemanw Wondered if it's possible for a Contact Layout Editor block to be open in edit mode by default when visiting a Contact Summary page? I've tried a delayed `$('#myblockID').click()` but it's clearly not as simple as that. Any pointers? Thanks!

**Comment by colemanw** [comment]
Sorry I didn't see this till now.
To open a block for editing, the contact summary page looks for a mouseup event:
https://github.com/civicrm/civicrm-core/blob/f679927c4376753da3228b61b1f9bf4c142972b6/templates/CRM/Contact/Page/View/Summary.js#L215-L219

**Comment by christianwach** [comment]
@colemanw That's great -- thank you!
