### ISSUE TITLE
Requires the API4 extension - needs updating to handle API4 in core.

### ISSUE THREAD

**Issue by MikeyMJCO** [civicrm/org.civicrm.contactlayout#62]
This needs updating probably now that API4 is in core?

Having this enabled prevents removal of API4 - this is likely to cause conflicts between the APIv4 extension and APIv4 in core. 

If we're happy with the approach I suggest bumping the required version for this extension to a post v4-in-core release and dropping the API4 extension requirement?

Happy to open the PR.

**Comment by colemanw** [comment]
Correct me if I've missed something, but this should continue to work fine as-is.

- Pre 5.19 this extension will require the api4 extension.
- Upgrading to 5.19 will automatically disable the api4 extension and remove the dependency.

So unless you've encountered a problem, I don't think there's anything to do.

**Comment by MikeyMJCO** [comment]
Yeah - sorry I thought the API4 merge dropped in 5.18 not 5.19 that is my mistake.
