### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by xpdientUK** [civicrm/org.civicrm.contactlayout#63]
Drupal 7.69, Civicrm 5.21.0 Editor v 1.4.3

Getting blank screen with console error when access Contact Layout editor

Failed to load resource: the server responded with a status of 403 () https://clubguests.net/civicrm/ajax/api4

**Comment by colemanw** [comment]
Try clearing caches and ensure your logged-in user has administer CiviCRM and access ajax api permissions.

**Comment by sunilpawar** [comment]
We have similar issue on two url:
https://sitename/civicrm/a#/contact-summary-editor
https://sitename/civicrm/contact/view?reset=1&cid=2

Drupal 8.8.4, CiviCRM 5.21.3, extension version 1.4.3

If contact layout configuration not present, then it load the screen, but if there is existing layout configuration available, then screen not loading correctly. 

Browser Console shows Error:

> angular.js?r=NwasM:14199 TypeError: $scope.layouts.unshift is not a function
>     at ChildScope.$scope.newLayout (https://sitename/sites/default/civicrm/extensions/org.civicrm.contactlayout/ang/contactlayout/contactlayout.js?r=NwasM:224:22)
>     at new <anonymous> (https://sitename/sites/default/civicrm/extensions/org.civicrm.contactlayout/ang/contactlayout/contactlayout.js?r=NwasM:451:14)
>     at Object.instantiate (https://sitename/libraries/civicrm/bower_components/angular/angular.js?r=NwasM:4786:14)



 ```
   $scope.newLayout = function() {
      var newLayout = {
        label: ts('Untitled %1', {1: ++newLayoutCount}),
        blocks: [[[],[]]]
      };
      $scope.deletedLayout = null;
      loadLayout(newLayout);
// unshift is not working ----
      $scope.layouts.unshift(newLayout);
      $scope.selectLayout(newLayout);
    };
```

CC @colemanw

**Comment by colemanw** [comment]
Sorry but I can't reproduce the problem. The screen loads fine for me if there are existing layouts or not.
If you want to email me with access creds to your site I'm happy to take a look.

**Comment by sunilpawar** [comment]
@colemanw i have identify the  issue.

here are changes 
```patch
diff --git a/Civi/Api4/services.xml b/Civi/Api4/services.xml
index 3d8a2fca..7ded2145 100644
--- a/Civi/Api4/services.xml
+++ b/Civi/Api4/services.xml
@@ -22,5 +22,9 @@
             <tag name="event_subscriber"/>
         </service>

+        <service id="api4.post_select_query.subscriber" class="Civi\Api4\Event\Subscriber\PostSelectQuerySubscriber">
+            <tag name="event_subscriber"/>
+        </service>
+
     </services>
 </container>
```

if this is missing then api4 return serialise/JSON encoded data as it is from table column.
e.g. civicrm_contact_layout have blocks, tabs column contain json data.

After these change, data get un-serialise/JSON decoded using following.
```
Civi/Api4/Query/Api4SelectQuery.php
	$event = new PostSelectQueryEvent($results, $this);
	\Civi::dispatcher()->dispatch(Events::POST_SELECT_QUERY, $event);
Calls:
Civi/Api4/Event/Subscriber/PostSelectQuerySubscriber.php
```

So nothing related to extension but its issue in core.

**Comment by colemanw** [comment]
That shouldn't be necessary. All APIv4 event subscribers are loaded in bulk:
https://github.com/civicrm/civicrm-core/blob/b0f06875baf28dc3917e34c4d35636c012f783f7/CRM/Api4/Services.php#L34

**Comment by sunilpawar** [comment]
@colemanw , i got the issue, we have setting in civicrm.settings.php file
After changing the path, it started working, no need to modify services.xml file

```patch
$civicrm_paths['civicrm.root'] = array(
  'url' => 'https://sitename/libraries/civicrm/',
-  'path' => 'SITE_PATH/web/libraries/civicrm/',
+  'path' => 'SITE_PATH/vendor/civicrm/civicrm-core/',
);
```

Thanks.

**Comment by colemanw** [comment]
Yes, having an incorrect path setting will cause some strange issues.
Maybe we need to make a status check for that.
