### ISSUE TITLE
Extension doesn't work: reloadModels

### ISSUE THREAD

**Issue by pvmaria** [civicrm/org.civicrm.contactlayout#67]
Hi there,

I have the same problem as described in [Issue ](https://github.com/civicrm/org.civicrm.contactlayout/issues/19) but all extensions are uptodate and it's still not working. Please help!

CiviCRM --> 5.24.5
Angular Profiles --> 4.7.31-1.1.2
Contact Layout Editor --> 1.4.3

![image](https://user-images.githubusercontent.com/50700452/83154783-d42cd000-a100-11ea-97fa-3c30ac17926a.png)

angular.js:14199 TypeError: Cannot read property 'reloadModels' of undefined
    at new <anonymous> (https://crm.x.com/sites/default/files/civicrm/persist/contribute/dyn/angular-modules.bb70020d2def5cd678e7a2850a64a542.js?qb1lno:1822:16)
    at Object.instantiate (https://crm.x.com/sites/all/modules/civicrm/bower_components/angular/angular.min.js?qb1lno:42:109)
    at https://crm.x.com/sites/all/modules/civicrm/bower_components/angular/angular.min.js?qb1lno:91:374
    at Object.link (https://crm.x.com/sites/default/files/civicrm/persist/contribute/dyn/angular-modules.bb70020d2def5cd678e7a2850a64a542.js?qb1lno:8306:274)
    at https://crm.x.com/sites/all/modules/civicrm/bower_components/angular/angular.min.js?qb1lno:16:71
    at sa (https://crm.x.com/sites/all/modules/civicrm/bower_components/angular/angular.min.js?qb1lno:82:244)
    at n (https://crm.x.com/sites/all/modules/civicrm/bower_components/angular/angular.min.js?qb1lno:68:6)
    at g (https://crm.x.com/sites/all/modules/civicrm/bower_components/angular/angular.min.js?qb1lno:59:428)
    at https://crm.x.com/sites/all/modules/civicrm/bower_components/angular/angular.min.js?qb1lno:59:67
    at https://crm.x.com/sites/all/modules/civicrm/bower_components/angular/angular.min.js?qb1lno:64:67 <div ng-view="" class="ng-scope">
(anonymous) @ angular.js:14095
DevTools failed to load SourceMap: Could not load content for chrome-extension://hnmpcagpplmpfojmgmnngilcnanddlhb/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by colemanw** [comment]
Does the error occur in all browsers and for all users?

**Comment by pvmaria** [comment]
Yes.

**Comment by pvmaria** [comment]
I've tried it again on another instance and now I get another error:

POST https://crm.x.com/civicrm/ajax/api4 500 (Service unavailable (with message))
  | send | @ | jquery.min.js?qb39zl:4
-- | -- | -- | --
  | ajax | @ | jquery.min.js?qb39zl:4
  | n.<computed> | @ | jquery.min.js?qb39zl:4
  | (anonymous) | @ | crm.ajax.js?qb39zl:73
  | CRM.api4 | @ | crm.ajax.js?qb39zl:60
  | crmApi4 | @ | angular-modules.377f…f547c9.js?qb39zl:23
  | data | @ | angular-modules.377f…47c9.js?qb39zl:1403
  | invoke | @ | angular.js:4774
  | (anonymous) | @ | angular-modules.377f…47c9.js?qb39zl:8315
  | q | @ | angular.js:335
  | m | @ | angular-modules.377f…47c9.js?qb39zl:8314
  | (anonymous) | @ | angular.js:16613
  | $eval | @ | angular.js:17958
  | $digest | @ | angular.js:17787
  | $apply | @ | angular.js:17958
  | (anonymous) | @ | angular.js:1808
  | invoke | @ | angular.js:4774
  | c | @ | angular.js:1808
  | Gc | @ | angular.js:1808
  | se | @ | angular.js:1715
  | (anonymous) | @ | angular.js:32489
  | i | @ | jquery.min.js?qb39zl:2
  | fireWith | @ | jquery.min.js?qb39zl:2
  | ready | @ | jquery.min.js?qb39zl:2
  | J | @ | jquery.min.js?qb39zl:2

**Comment by pvmaria** [comment]
I've fixed it. Some files were missing on the server.
