### ISSUE TITLE
SEPA Mandate: not part of it?

### ISSUE THREAD

**Issue by pvmaria** [civicrm/org.civicrm.contactlayout#68]
Hey there,
We've installed the extension and it works pretty well. 
There is only one thing: We can't configure the Tab "SEPA Mandate". It does not seem to be part of it.
It would be nice if we could choose in which order it should be visible.
Thanks in advance!

**Comment by colemanw** [comment]
SEPA Mandate is not part of CiviCRM, so I'm guessing this is a customization for you.
Is it custom fields, or something provided by an extension?

**Comment by pvmaria** [comment]
Thanks for you quick response, @colemanw. This is CiviSEPA, one of SYSTOPIA's extensions. They are injected by hook. Is there a way to make this visible?

**Comment by colemanw** [comment]
Yes, I think they just need to update their hook implementation. There are 2 hooks for adding a tab to the contact summary screen; one of them is deprecated, so they just need to switch their extension to use the non-deprecated one and then it will work with this extension :)

**Comment by tttp** [comment]
@pvmaria if not done already, could you add it as an issue on civisepa project? https://github.com/Project60/org.project60.sepa/issues

**Comment by colemanw** [comment]
This was fixed by https://github.com/Project60/org.project60.sepa/issues/574
