### ISSUE TITLE
I did a gif

### ISSUE THREAD

**Issue by eileenmcnaughton** [civicrm/org.civicrm.contactlayout#7]
Posting this here in case you can use it - shows collapsible config

![collapsibleconfig](https://user-images.githubusercontent.com/336308/43874943-aacae6a4-9be2-11e8-8a04-2cbf0ef04a9a.gif)

**Comment by colemanw** [comment]
FYI I've pushed up some changes to the wording and the style based on user feedback. So this GIF is now a bit out of date.
