### ISSUE TITLE
Tabs do not show after upgrade to 5.26.2

### ISSUE THREAD

**Issue by andyburnsco** [civicrm/org.civicrm.contactlayout#70]
I upgraded to 5.26.2 and now on the contact summary layout editor the tabs do not show, only the summary tab.

![Capture](https://user-images.githubusercontent.com/18341942/86609148-20292b00-bf71-11ea-8a46-1dd8c0e34c8f.PNG)

If I try and make a brand new layout, all the tabs show.

If I try and save an existing the layout it creates a second summary tab. When I click the x to hide it, it turns into one of my custom fieldset tabs. The first summary tab does this as well.

![image](https://user-images.githubusercontent.com/18341942/86610201-9e3a0180-bf72-11ea-997d-4a568aa81b2e.png)

Here are console errors if relevant.

![image](https://user-images.githubusercontent.com/18341942/86609265-59619b00-bf71-11ea-87e5-99db42ac55a0.png)

Reverting to version 1.4.3 had no effect.

**Comment by colemanw** [comment]
What version did you upgrade from?

**Comment by andyburnsco** [comment]
> 
> 
> What version did you upgrade from?

5.24.4

**Comment by colemanw** [comment]
And you are using v1.5?

**Comment by andyburnsco** [comment]
> And you are using v1.5?

Yes

**Comment by colemanw** [comment]
OK I was able to reproduce this by building a 5.24.4 site, adding a couple of layouts, and then upgrading the site to 5.29 - the tabs appear to be missing:
![image](https://user-images.githubusercontent.com/2874912/86631025-9d699580-bf9b-11ea-9712-bf8b3e722827.png)

**Comment by colemanw** [comment]
I've fixed the bug and released v1.5.1 of this extension.
See c049215955d2988abaf7ad07430691578558548d
