### ISSUE TITLE
Supporting relationships between different contact types

### ISSUE THREAD

**Issue by reneolivo** [civicrm/org.civicrm.contactlayout#71]
Currently we can display blocks for related contacts. We can display a contact's supervisor, sibling, or children.

What we don't currently support is displaying blocks for relationships between different contact types. For example: Employee and Employer.

We want to add support to this kind of scenario as follows:

Enabling blocks when they have the right relationship for the viewing contact type and the block's contact type:
![gif (7)](https://user-images.githubusercontent.com/1642119/87315513-8de5d180-c4f2-11ea-8bb8-765b7e260e16.gif)

Displaying the block:
![Screen Shot 2020-07-10 at 5 51 57 PM](https://user-images.githubusercontent.com/1642119/87315753-cbe2f580-c4f2-11ea-8c18-bde9bd05ea0f.png)

**Comment by colemanw** [comment]
Cool
