### ISSUE TITLE
Contact Summary Layout screen does not display correctly

### ISSUE THREAD

**Issue by mfuggle** [civicrm/org.civicrm.contactlayout#78]
I have tried to install the Contact Layout extension and get the following issue shown in the attached screen shot. I am using 

- Drupal 7.72
- CiviCRM 5.24.3
- Contact Summary Layout 1.7.1
- Angular Profiles 4.6-1.0.2

I wonder if someone might point me in the right direction to get this resolved.

![image](https://user-images.githubusercontent.com/1777429/93147237-03a92c00-f734-11ea-8696-57ba24bc2d0b.png)

**Comment by colemanw** [comment]
Hi @mfuggle could you please press `F12` in your browser to open up the console, then refresh the page and screenshot the error message that shows up in the console?

**Comment by mfuggle** [comment]
Screenshot of Java console log is attached.

![2020-09-15_14-28-12](https://user-images.githubusercontent.com/1777429/93165803-62849a80-f760-11ea-818f-6ab874c0099b.jpg)

**Comment by colemanw** [comment]
I'm not able to reproduce that problem locally. If you've recently upgraded you may need to clear your caches.

**Comment by mfuggle** [comment]
I have cleared all caches and still get the same result.

**Comment by colemanw** [comment]
While on that same screen, please type `CRM.vars.contactlayout` into your console (at that little blue prompt at the bottom) and press enter, and show me the resulting output.

**Comment by colemanw** [comment]
Ok I think I found the solution. Can you please try this fix: #79

**Comment by mfuggle** [comment]
I'm a bit lost in trying to apply a 'fix'. I was expecting to find a .patch file. I have searched for instructions on applying a fix but am still confused. Could I impose on you to point me in the right direction?

**Comment by colemanw** [comment]
It's a GitHub pull-request, which is a patch plus description, comments, unit-testing, etc (sort of like the difference between a raw jpg and a jpg posted on facebook).
You can download the raw patch file here: https://patch-diff.githubusercontent.com/raw/civicrm/org.civicrm.contactlayout/pull/79.diff

**Comment by mfuggle** [comment]
Many thanks - I obviously need to get up to speed with Git Hub which I will start to do. Apologies for the trouble. I'll apply the patch later today and post the outcome when I have tested it.

**Comment by mfuggle** [comment]
#79 corrected the issue. Many thanks...
