### ISSUE TITLE
Bypass contact add screen

### ISSUE THREAD

**Issue by michaelmcandrew** [civicrm/org.civicrm.contactlayout#81]
This is a rally nice extension.

One thing that stands out for me as an administrator wanting to simplfy contact screens for users is that this extension does not simply the add contact screen.

It would be nice to be able to address that and I am wondering how we might approach that.

A very hacky approach might be to:

- intercept calls to https://example.org/civicrm/contact/add?reset=1&ct=Organization
- create a new contact of the type specified with no fields filled in (maybe the API can bypass required field requirements)
- redirect to https://example.org/civicrm/contact/view?reset=1&cid=N

One problem with this approach is that we would always be creating new blank contacts. Not sure how acceptable that would be to people and/or if there is a way to clear up contacts that ended up not being saved.

There may be other problems I am not aware of. Interested to know peoples thoughts on this and if there are other approaches to consider.

Setting it as an (experimental) option would be one way of getting going on this without disrupting current users. I suppose it could even be a completely separate extension.

**Comment by colemanw** [comment]
The afform extension, which has now been merged into the `civicrm-core` git repo, is still "beta" but with a little more polish it should be able to replace the contact add/edit form.

In the short-term, there's the old "quick add" drupal block which creates a simple contact with name & email, then lets you do the rest on the summary screen.

**Comment by michaelmcandrew** [comment]
thanks for the feedback @colemanw

**Comment by colemanw** [comment]
No prob
