### ISSUE TITLE
Summary Layout Editor page blank after extension update to 1.7.2

### ISSUE THREAD

**Issue by elliottmart** [civicrm/org.civicrm.contactlayout#83]
Problem: contact summary layout page blank (It just shows a link to CIVICRM with the words ‘Unknown path’. ) after apparently successful extension update to 1.7.2 on Civicrm 5.23.4 and Wordpress 5.4.1.  (The CIVICRM link takes me to the civi dashboard.)
- the existing summary layout still appears to display fine on the contact screen but there is no way to make changes on the Summary Layout page anymore?
- if I disable, uninstall and re-install does it lose my current layout?

**Comment by colemanw** [comment]
You can disable and re-enable without losing data. But if you uninstall and re-install then yes you will lose your layouts.
Before doing that I would try clearing caches.

**Comment by elliottmart** [comment]
Thanks for the advice. Is that “Settings - Cleanup Caches and Update Paths”? Then “Cleanup Caches?” That doesn’t interfere with my site does it?

**Comment by colemanw** [comment]
Correct.

**Comment by elliottmart** [comment]
Perfect. Cleanup Caches worked great! I’m back in business with the Summary Layout Editor. Thanks so much for the quick help and such an excellent extension!!! I love being able to customize the contact summary screen!

**Comment by colemanw** [comment]
You're welcome!
