### ISSUE TITLE
Custom field sets displayed regardless of contact subtype

### ISSUE THREAD

**Issue by chumkui** [civicrm/org.civicrm.contactlayout#84]
This is a great extension - thanks!  I have created a couple of layouts and they work well except for the fact that custom field sets are displayed (with no data) if contact is not of that type.  

Say I have a set of custom fields called MyCustomFieldSet that are displayed and get populated for a particular contact subtype, Individual - MySubType.  Normally when I view the summary, only if the record is of that subtype will I see the field set displayed.  

I want to create a general layout for all individual types regardless of subtype, but perhaps want to remove demographic and other data that is not used for a particular of group of users.  I create a layout with the extension for that group of users that includes that custom set of fields.  What I end up with is the custom field set displayed, but blank.

I think the behaviour should be as it would normally be i.e. only if the custom field set is relevant to the subtype will it be displayed.

**Comment by colemanw** [comment]
Agree this would be nice to fix. Do you have the ability to make a patch for this?

**Comment by chumkui** [comment]
> Agree this would be nice to fix. Do you have the ability to make a patch for this?

I have taken a quick look at this and it's a bit above my 'PHP pay grade' I'm afaid :-)  I think I can see where it is not working.  The normal Summary.php (line 43) creates a $GroupTree array containing only the relevant set of custom fields for a given Contact type and sub type.  This is a fundamentally different approach to ContactLayout.php in the extension that seems to treat all custom field sets as equal.  

I'll treat this as a learning exercise and take a look with a colleague.  Don't hold your breath for a fix from me, but I will take a look!

**Comment by colemanw** [comment]
That's helpful thanks @chumkui - helped me track down the variable that Civi assigns to the template of which custom groups are applicable to the current contact. Now fixed.

**Comment by chumkui** [comment]
@colemanw  - Thanks, but I think you are being generous there.  I have looked at your fix and clearly the path I was thinking going down (not in the TPL) was clearly well off base.  Lots to learn about how all this fits together.  Many thanks. 

**However**...  Now, standard (i.e. non editable) blocks that were once excluded are _now included_.  I created a layout for a group of staff, removing the IM and the Demographics block as well as many other custom blocks.  The custom blocks work as expected now (many thanks) but I cannot seem to get rid of any standard blocks.

**Comment by colemanw** [comment]
@chumkui I'm not sure I understand. Can you send a screenshot or two to illustrate the problem?

**Comment by chumkui** [comment]
@colemanw  - Really sorry, I reckon its cacheing in some way. Ignore me for the moment -  I'll see what is going on and revert.  Its taken me a bit of time as I missed the addition of the Bundle change and am running the LTS 5.27.7, so needed to clear it all out and reinstall before I realised there were two changes...

**Comment by chumkui** [comment]
@colemanw OK - I have started from scratch and I think there is an issue on my system (latest Drupal and CiviCRM 5.27.7LTS)

I have made a really simple example whereby I have made two layouts for two groups, with the second group more restrictive.  Screenshots attached!  Many thanks.
![layout_2](https://user-images.githubusercontent.com/18424420/98846939-8e15bf80-2447-11eb-94ed-ea5608b3bd15.png)
![layout_1](https://user-images.githubusercontent.com/18424420/98846944-8f46ec80-2447-11eb-9eb5-21c2ab57ffd3.png)

**Comment by colemanw** [comment]
Ah. I see your problem. Look at the left side of your first screenshot. You have 2 layouts, "Head Office Admin Group" is placed above "Staff". This extension prioritizes layouts from top to bottom. So the top layout will always take priority, and since it is set to show to "All users" it will trump the second layout every time.

Switch the order and it should work the way you were expecting. With the "Staff" layout as the top priority, it will be shown if the user is a member of the "Staff" group. All other users will see the second layout (if it applies to them) and so on down the list of layouts.

**Comment by chumkui** [comment]
Hi Coleman - Many thanks. I was vaguely aware of this.  I think this may not work for me due to the nature of our groups and ACLs.  We have a general set (Group) of Staff and few other sets that bisect with this.  I had assumed that it would pick up the groups in order, but I do not think this is the case.  We use ACLs to lock down a variety of fields for records.  I'll have to go away and have a think about how this might work in our set up.

Thanks for looking at this and all the assistance.
