### ISSUE TITLE
Take a look at the Caldera Forms WordPress plugin

### ISSUE THREAD

**Issue by paaljoachim** [civicrm/org.civicrm.contactlayout#9]
Hey

It looks like big changes are happening to Civicrm. I checked it out a long time ago and it looks like I need to check it out again.

I use Caldera Forms WordPress plugin on a few sites. It has a very nice drag and drop feature.
https://wordpress.org/plugins/caldera-forms/

![screen shot 2018-08-15 at 14 17 17](https://user-images.githubusercontent.com/5323259/44147811-fb60890e-a095-11e8-88e6-5bf2854c3dfc.png)

With creating columns, duplication, drag/drop and more.

I am sharing this as an extra inspiration on what you are creating.

**Comment by danaskallman** [comment]
hey @paaljoachim sorta related, have you seen [Caldera Forms CiviCRM (CFC) plugin](https://github.com/mecachisenros/caldera-forms-civicrm/)

**Comment by colemanw** [comment]
Very cool! I'm pleased to see how much progress has been made on the Caldera CiviCRM plugin.
I'm closing this issue since there is nothing actionable, but thanks for sharing that info.
