### ISSUE TITLE
Primary phone number does not save when included as part of a profile

### ISSUE THREAD

**Issue by scoobird** [civicrm/org.civicrm.contactlayout#91]
Noticed this with profiles created as blocks within contact layout editor as well as ones set up the traditional way. If you leave location of the phone as primary, the phone number is visible and appears editable in the block, but doesn't save when text is changed. When a location type other than Primary is specified it works as expected.

**Comment by colemanw** [comment]
To clarify your bug report, are you saying that regular profile forms within CiviCRM (unrelated to this extension) have the same problem of being unable to save Primary Emails?

**Comment by scoobird** [comment]
Nope, not an issue with Civi profiles (at least not that I've noticed)! Within the context of this extension -- it doesn't matter how the profile was created. Hope that helps?

> To clarify your bug report, are you saying that regular profile forms within CiviCRM (unrelated to this extension) have the same problem of being unable to save Primary Emails?

**Comment by colemanw** [comment]
I tried this on my local test site (running the latest version of Civi + ContactLayout)

1. Create a layout
2. Click the **+ Block** button
3. In the "Unnamed profile" dialog, add 1 field to the profile: "Email (Primary)"
4. Create a new contact
5. From their summary screen, click the profile block to add an email address (works)
6. Observe new email address appears in the block
7. Click the block again to edit the email address (also works)

With these steps I am unable to reproduce the bug.

**Comment by scoobird** [comment]
Those were the steps I followed, but it is updating the Primary Phone field where I experience the issue, not email. Thanks!

**Comment by colemanw** [comment]
Ok I was able to reproduce for Phone field. Can you try out the fix linked above?
Or if you prefer a patch, here it is: https://patch-diff.githubusercontent.com/raw/civicrm/civicrm-core/pull/19321.diff

**Comment by scoobird** [comment]
Thank you @colemanw -- I tested and can confirm it's resolved
