### ISSUE TITLE
Fatal error when upgraded Civi core to 5.34.0

### ISSUE THREAD

**Issue by albionbrown** [civicrm/org.civicrm.contactlayout#93]
Using:
- Drupal 7
- CiviCRM 5.34.0
- PHP 7.1
- Contact Summary Layout extension 1.8.1

Before the update, we were on Civi core 5.20.0 which was working all ok. But, after upgrading to Civi core 5.34.0, a fatal error is now produced. I believe this to be a similar issue that org.compucorp.civicase has [here](https://github.com/compucorp/uk.co.compucorp.civicase/issues/721) in that it's missing a function that Civi core is expecting. 

The error presented is:
`Error: Class name must be a valid object or a string in _civicrm_api3_basic_get() (line 1247 of /var/www/portal/sites/all/modules/contrib/civicrm/api/v3/utils.php).
`

I had a step through and reached line 349 of api/v3/utils.php where it checks to see if _civicrm_api3_contact_layout_DAO is a function that exists, but it isn't declared anywhere.

**Comment by colemanw** [comment]
What version of this extension are you using?

**Comment by albionbrown** [comment]
1.8.1

**Comment by colemanw** [comment]
I just did a quick test and created a simple layout with a couple blocks & viewed a contact, and it didn't crash. So I'll need more detailed steps to reproduce. What other extensions do you have enabled? (and have you tried disabling all of them except for this one to see if the problem persists?) What layouts do you have and do any of them contain custom blocks? What "Show: ___ To: ___" criteria are you using for the layouts?

**Comment by albionbrown** [comment]
We're using other extensions like uk.co.compucorp.civicase, org.civicrm.shoreditch, org.civicoop.civirules and some others. I tried disabling/enabling as many modules I could but nothing changed. After playing with the civicrm.settings.php file, I managed to get it to work. I reflected these changes on other environments that are largely the same (mainly path changes) but no luck. Getting the "Unknown path" error when I try to access the contact lyout summary page under Administer > customize Data & Screens. Do you have any suggestions about civicrm.settings.php could be set up

**Comment by albionbrown** [comment]
Apologies for the inconvinience. I'd only now just looked at the contactlayout.xml file in the Menu directory to see that the URL is civicrm/admin/contactlayout instead of what I was previously using - civicrm/a/#/contact-layout-editor. As to what the missing function was, I'm not sure what's changed but it's decided to work now!

**Comment by colemanw** [comment]
Great I'm glad you got it working.

FYI the nav menu should have updated automatically for you:

https://github.com/civicrm/org.civicrm.contactlayout/blob/544b80ee46aceae679566bb7d4e354820247a4eb/CRM/Contactlayout/Upgrader.php#L102-L112

Perhaps extension upgrades didn't get run on your site?

**Comment by nielosz** [comment]
I do face this issue with 5.37.2 and some extensions like Dataprocessor (https://lab.civicrm.org/extensions/dataprocessor) and expenses (https://lab.civicrm.org/extensions/expenses). How did you fix it? I reviews civicrm.settings.php and tried everything which I know from years of civicrm experience. See https://civicrm.stackexchange.com/questions/39963/group-of-unsolvable-api-and-core-errors as well.

**Comment by colemanw** [comment]
@nielosz I'm reading your StackExchange post and I don't understand how that error relates to this one - are you using this extension at all?

You can message me at https://chat.civicrm.org @colemanw if you want to pay for Core Team consulting help.

**Comment by nielosz** [comment]
Hi @colemanw and thx! I thought the relationship is the missing api call registration.
