### ISSUE TITLE
Region references removed when replaced by ext block

### ISSUE THREAD

**Issue by jitendrapurohit** [civicrm/org.civicrm.contactlayout#96]
We added a minor change using the region reference on the contact summary page https://docs.civicrm.org/dev/en/latest/framework/region/

```php
CRM_Core_Region::instance('contact-basic-info-right')->add([
  'markup' => "<div class='crm-content'><a href=/admin/single-membership-card/{$contactID}>Download Membership Card Data</a></div>",
]);
```

`contact-basic-info-right` is this block 

![image](https://user-images.githubusercontent.com/5929648/115178216-75908c00-a0ee-11eb-94ed-4ee4b98a98d5.png)

Thought the region reference would still be there if we added this block to the layout. But no, it rendered the tags, etc with no display of the above custom link. 

We've now fixed this with the `hook_civicrm_contactSummaryBlocks()` easily but think it should have been already handled?

Is region reference supported with this ext?

**Comment by colemanw** [comment]
Most of the regions defined on that page don't make sense for a flexible layout.
But in this case, I think that region is fine to add. Here:
50ce952e0bb2e36f12cef23a1f5982ee60ebad43

**Comment by jitendrapurohit** [comment]
Thanks for the quick fix @colemanw 👍

**Comment by colemanw** [comment]
I've reverted the commit because it caused #102.
I think a better solution would be to add a new region to `templates/CRM/Contact/Page/ContactImage.tpl`

**Comment by colemanw** [comment]
@jitendrapurohit can you review civicrm/civicrm-core#20662

**Comment by jitendrapurohit** [comment]
Hi @colemanw 

The core PR does its job by adding a new region to the image block. +1 to the change. But i'm not sure how it helps in resolving this problem? 

The main issue here was civi offering few region names, eg `contact-basic-info-right` allowing you to add some custom template changes to the contact summary page. We used this method to add some HTML markup on the page.

These custom markups were removed after we installed contactlayout extension and enabled those blocks on the page.

This problem is still there. Am i correct the only way to restore those regions is to add another hook `hook_civicrm_contactSummaryBlocks()` as I've mentioned in the ticket description?

>Most of the regions defined on that page don't make sense for a flexible layout.
>But in this case, I think that region is fine to add. Here:


I'm all fine with the first stmt as we already came up with the contactSummaryBlocks() hook fix. Just need to make sure the problem is clearly recorded here :)

Thanks,
Jitendra.

**Comment by colemanw** [comment]
Maybe I misunderstood your original issue, I thought you were trying to use regions to alter the contact image.

If you wanted to add a new block then yes `hook_civicrm_contactSummaryBlocks()` is the way to go.

**Comment by colemanw** [comment]
@jitendrapurohit FYI I do not recommend using the `hook_civicrm_contactSummaryBlocks()` to reimplement the `contact-basic-info-right` region inside a block.

As documented in #102 the regions on the contact summary page are just not compatible with this extension and I don't think they ever will be.

Could you please leave a review comment on civicrm/civicrm-core#20662 so we can either merge it or close it?
