### ISSUE TITLE
User ID does not appear to be available for putting in to a new block

### ISSUE THREAD

**Issue by petednz** [civicrm/org.civicrm.contactlayout#97]

**Comment by colemanw** [comment]
User id or Contact id?

**Comment by petednz** [comment]
User ID

![image](https://user-images.githubusercontent.com/5800574/116318972-ce0c0b80-a809-11eb-8ab8-423d764a9d89.png)

**Comment by colemanw** [comment]
Guess not. Those are Civi Profiles, and it makes sense that field hasn't been exposed as a profile field.

**Comment by petednz** [comment]
so Close as not fixable?

**Comment by colemanw** [comment]
Yes, although I think there's a good chance that SearchKit will solve this need. It's already able to create contact summary blocks, so I think it's just a matter of adding an APIv4 entity for UF.
